# Generated by Django 3.2.8 on 2022-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220303_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=2, upload_to='news/%Y/%m/%d/', verbose_name='Фоновое-Изображение'),
            preserve_default=False,
        ),
    ]
