# Generated by Django 3.2.8 on 2022-01-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Загаловок')),
            ],
            options={
                'verbose_name': 'Загаловоки строк в таблицах',
            },
        ),
        migrations.CreateModel(
            name='Table_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('count', models.IntegerField(blank=True, verbose_name='Количевство в месяц')),
                ('totality', models.IntegerField(blank=True, verbose_name='Совокупность в месяц')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт в таблице',
                'verbose_name_plural': 'Продукт в таблице',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.table_product')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
