# Generated by Django 3.2.8 on 2022-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table_headers',
            options={'verbose_name': 'Загаловоки строк в таблицах', 'verbose_name_plural': 'Загаловоки строк в таблицах'},
        ),
        migrations.AddField(
            model_name='table_product',
            name='price_device',
            field=models.IntegerField(blank=True, default=100, verbose_name='Доступно за 1 апарат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table_product',
            name='price_per_quantity',
            field=models.IntegerField(blank=True, default=1000, verbose_name='Доступная цена за количевство апаратов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table_product',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Количевство в месяц'),
        ),
    ]
