# Generated by Django 3.2.8 on 2022-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Загаловок'),
        ),
    ]
