# Generated by Django 3.2.8 on 2022-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_product',
            name='is_solid',
            field=models.BooleanField(default=False, verbose_name='Закрасить'),
        ),
    ]
