# Generated by Django 3.2.8 on 2022-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_product',
            name='price_per_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступная цена за количевство апаратов'),
        ),
    ]
