# Generated by Django 3.2.8 on 2022-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220128_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_product',
            name='price_device',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступно за 1 апарат'),
        ),
        migrations.AlterField(
            model_name='table_product',
            name='price_per_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступная цена за количевство апаратов'),
        ),
    ]
