# Generated by Django 3.2.8 on 2022-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_device_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
