# Generated by Django 3.2.8 on 2022-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220128_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_product',
            name='totality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Совокупность в месяц'),
        ),
    ]
