# Generated by Django 3.2.8 on 2022-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_table_product_totality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_product',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количевство в месяц'),
        ),
        migrations.AlterField(
            model_name='table_product',
            name='totality',
            field=models.FloatField(blank=True, null=True, verbose_name='Совокупность в месяц'),
        ),
    ]
