# Generated by Django 3.2.8 on 2022-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Фоновое-Изображение')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Характеристика')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/%d/', verbose_name='Фоновое-Изображение')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша исполнительная команда',
            },
        ),
    ]
